### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by GuyliannEngels** [joffrey-thulier/joffrey-thulier-blog#1]
@joffrey-thulier ,

Tu n'as ajouté disqus sur ton blog. Ajoute disqus le plus vite possible

**Comment by GuyliannEngels** [comment]
Je peux voir que tu as ajouté disqus sur ton blog. C'est une bonne chose mais n'oublie pas dans ce cas de répondre à l'ISSUE et de la fermer ensuite.

**Comment by joffrey-thulier** [comment]
Bonjours,

excusez moi mais je ne comprend pas de quelle ISSUE vous parlez ?
celle pour la biométrie humaine et le zooplankton ?
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : jeudi 24 octobre 2019 06:49
À : joffrey-thulier/joffrey-thulier-blog <joffrey-thulier-blog@noreply.github.com>
Cc : Joffrey THULIER <Joffrey.THULIER@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [joffrey-thulier/joffrey-thulier-blog] disqus (#1)


Je peux voir que tu as ajouté disqus sur ton blog. C'est une bonne chose mais n'oublie pas dans ce cas de répondre à l'ISSUE et de la fermer ensuite.
