### ISSUE TITLE
problème avec tes images

### ISSUE THREAD

**Issue by GuyliannEngels** [joffrey-thulier/joffrey-thulier-blog#2]
Suite à tes mails, j'ai décidé de te répondre par ISSUE

Il semble que tu as un problème d'accès à tes images et cela est semble t'il tout à fait normal.

Tu utilises dans ton préambule 

```
preview: baleine.jpg
```

Cependant dans le dossier _posts, tu as un dossier 2029-11-01-article-2 qui comprend

- un fichier .RMD (ton artice)
- un dossier image (avec tes images d'intérêts)
        +  baleine.jpg

En suivant ta structure, tu devrais donc mettre 

```
preview: image/baleine.jpg
```

Cela t'aide ?

**Comment by joffrey-thulier** [comment]
oui merci beaucoup

**Comment by GuyliannEngels** [comment]
Il ne te reste plus qu à fermer l issue :)
